replicaCount: 1

image:
  repository: ghcr.io/savinovvu/hactions/hactions
  tag: master-d2fa8c8
  pullPolicy: IfNotPresent

app:
  name: "hello-spring"
  port: 8080  # <-- ДОБАВЬТЕ ЭТУ СТРОКУ

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 15
  periodSeconds: 5