apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-spring-app.fullname" . }}
  labels:
    {{- include "hello-spring-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-spring-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-spring-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: SPRING_APPLICATION_NAME
              value: "{{ .Values.app.name }}"
            - name: SERVER_PORT
              value: "{{ .Values.app.port }}"
#           livenessProbe:
#             httpGet:
#               path: {{ .Values.livenessProbe.path }}
#               port: {{ .Values.app.port }}
#             initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
#             periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
#           readinessProbe:
#             httpGet:
#               path: {{ .Values.readinessProbe.path }}
#               port: {{ .Values.app.port }}
#             initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
#             periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}