{{- if or .Values.spring.datasource.username .Values.spring.datasource.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-spring-app.fullname" . }}-db-secret
  labels:
    {{- include "hello-spring-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.spring.datasource.username | b64enc }}
  password: {{ randAlphaNum 16 | b64enc }}
{{- end }}
